import { expect, test } from '@playwright/test'

test.describe('MediaMTX API Connectivity', () => {
  test('should connect to MediaMTX API', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    expect(body).toHaveProperty('itemCount')
    expect(body).toHaveProperty('items')
  })

  test('should return streams list', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    expect(Array.isArray(body.items)).toBe(true)
  })

  test('should have fake streams running', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    expect(body.itemCount).toBeGreaterThanOrEqual(1)
  })

  // The dev fleet is deliberately diverse (see mediamtx.dev.yml +
  // examples/fake-streams): the five wildcard-backed stream1..5 plus named
  // always-on / on-demand / offline cameras. So the list is larger than the
  // wildcard streams alone, and not every path is ready (on-demand paths are
  // idle until viewed; service-elevator has no source).
  test('should list at least the five wildcard streams plus a named camera', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    expect(body.itemCount).toBeGreaterThanOrEqual(6)
  })

  test('should have correct stream names', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    const streamNames = body.items.map((item: { name: string }) => item.name)
    expect(streamNames).toContain('stream1')
    expect(streamNames).toContain('stream2')
    expect(streamNames).toContain('stream3')
    expect(streamNames).toContain('stream4')
    expect(streamNames).toContain('stream5')
    // A named, always-on camera generated by MediaMTX itself (runOnInit).
    expect(streamNames).toContain('front-door')
  })

  test('the always-on streams are marked as ready', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/paths/list')
    expect(response.status()).toBe(200)
    const body = await response.json()
    const alwaysOn = ['stream1', 'stream2', 'stream3', 'stream4', 'stream5', 'front-door']
    const readyByName = new Map(
      body.items.map((item: { name: string, ready: boolean }) => [item.name, item.ready]),
    )
    for (const name of alwaysOn) {
      expect(readyByName.get(name), `${name} should be ready`).toBe(true)
    }
  })

  test('should return global config', async ({ request }) => {
    const response = await request.get('http://localhost:9997/v3/config/global/get')
    expect(response.status()).toBe(200)
    const body = await response.json()
    expect(body).toHaveProperty('hlsAddress')
    expect(body).toHaveProperty('api')
    expect(body.api).toBe(true)
  })
})

test.describe('MediaMTX HLS Endpoints', () => {
  test('should serve HLS endpoint', async ({ request }) => {
    const response = await request.get('http://localhost:8888', {
      failOnStatusCode: false,
    })
    expect([200, 404]).toContain(response.status())
  })
})
